### ISSUE TITLE
Problem at starting app: "Ason could not find information to login..."

### ISSUE THREAD

**Issue by leillo1975** [FranjeGueje/Ason#3]
Hello

I have the following message at start:
![Captura de pantalla de 2023-04-22 13-20-44](https://user-images.githubusercontent.com/551821/233781350-bd3169fd-17af-4a9d-9cec-88ce3c7545d6.png)

It then closes and reopens in a loop.

**Comment by FranjeGueje** [comment]
Hi Leo,

The nile versión that is packed in "the full pack" on releases is compiled (packed) in a Steam Deck (Steam OS).

I think your issue is the glibc version. Steam OS, Arch, Manjaro is using this version. What is your OS version? Ubuntu?

Regards

**Comment by leillo1975** [comment]
Package: glibc-source
Version: 2.35-0ubuntu3

I use Ubuntu 22.04

**Comment by FranjeGueje** [comment]
The version of glibc in full pack for steamos is 2.36. This is the issue.

In bin dir, I think yad and jq are valid but nile not. You should create a valid "nile" bin or script that works in your version. 

You can visit the page of nile to create a nile bin.
Write me if you want I send you info.

It's possible that I build a script to help this issue.

**Comment by FranjeGueje** [comment]
Hi again,
You can use a new script named "nile" from [https://raw.githubusercontent.com/FranjeGueje/Ason/master/BUILD/nile](url)
I just uploaded it.

**Replace the "bin/nile" file with this one.**

If you look inside, this script will download nile into a subfolder and you will be able to run nile.
Check if you want.

Ciao...

PS: you need python3 and pip3

**Comment by leillo1975** [comment]
I am still having problems. I have to install python3.10-venv, and then I have this error:

`leo@SYS-ADMIN:~/Escritorio/Ason$ ./Ason.sh 
/usr/bin/python3
/home/leo/Escritorio/Ason/bin/nile: liña 11: /home/leo/Escritorio/Ason/bin/nile.venv/bin/activate: Non hai tal ficheiro ou directorio
/usr/bin/python3
/home/leo/Escritorio/Ason/bin/nile: liña 11: /home/leo/Escritorio/Ason/bin/nile.venv/bin/activate: Non hai tal ficheiro ou directorio
^[/usr/bin/python3
/home/leo/Escritorio/Ason/bin/nile: liña 11: /home/leo/Escritorio/Ason/bin/nile.venv/bin/activate: Non hai tal ficheiro ou directorio
`

There are not a activate file on the bin folder

**Comment by FranjeGueje** [comment]
Hi Leo,

Don't you have the  bin/activate file?
It's part of python venv... It's strange...

What's the content of nile.venv?

**Comment by leillo1975** [comment]
Here is a screenshot of the nile.venv folder:

![Captura de pantalla de 2023-04-26 11-08-56](https://user-images.githubusercontent.com/551821/234527754-6f405cb7-411a-418f-bdf1-d2602a9a9932.png)

**Comment by FranjeGueje** [comment]
Hi Leo,
I'm thinking about this. It's possible that the venv was created before you install python-venv.
Please, delete this folder and try again. The subfolder nile.venv will be recreated again.

Regards!

**Comment by leillo1975** [comment]
You are right. Now seems to work. Thanks a lot for your support, and of course for this App. Let's try to play WRC9!

**Comment by FranjeGueje** [comment]
I'll add a new release in the future with the nile script with name "generic".
